### ISSUE TITLE
JWT 을 검증 및 식별하는 API 가 필요합니다.

### ISSUE THREAD

**Issue by a2tt** [Together-Coding/Authentication-Server#4]
# 개요

다른 서버 (ex. Runtime container) 에서 유저로부터 JWT 를 받았을 때, 이 토큰이 사용 가능한지 검증하고, JWT 안에 있는 정보를 추출하여 반환 할 서버가 필요합니다.

각 서버별로 역할이 나눠져 있고, JWT secret key 는 auth server 에서 관리할 것이기 때문에, 이렇게 따로 요청 드립니다.

# 요청 예시
```plaintext
POST /.../validate
Content-Type: `multipart/form-date` or `application/json`
```

```json
{
  "token": "token.to.validate"
}
```

# 응답 예시
```
Content-Type: `application/json`
```

```json
{
  "valid": "<bool>",
  "user_id": "<int>",
  "expires_at": "<timestamp: JWT 의 만료 시각>",
  "...": "..."
}
```

**Comment by chasw0326** [comment]
네 알겠습니다

**Comment by chasw0326** [comment]
post의 의미랑 상이 한거 같아서 get으로 구현했는데 쿼리스트링으로 jwt를 노출해도 괜찮을까요?

**Comment by a2tt** [comment]
@chasw0326
HTTPS 사용하면 query string도 암호화가 되기는 하지만, 
[What is the difference between GET and POST encryption?](https://stackoverflow.com/questions/3063530/what-is-the-difference-between-get-and-post-encryption#:~:text=The%20data%20contained,the%20client%20computer.) 이런 이유로 POST 가 더 마음이 편할 것 같기는 하네요.

**Comment by chasw0326** [comment]
단순히 restful로 하고 싶어서 get으로 구현했는데, 길이나 보안까지 신경쓰면 확실히 post가 낫겠습니다. 수정하겠습니다
https://stackoverflow.com/questions/19637459/rest-api-using-post-instead-of-get
https://stackoverflow.com/questions/4203686/how-can-i-deal-with-http-get-query-string-length-limitations-and-still-want-to-b
오늘도 하나 알아가네요...

**Comment by chasw0326** [comment]
수정했습니다.
